version: "3"

services:
  message-broker:
    image: emqx:5.6.1
    container_name: message-broker
    environment:
      - "EQMX_NODE_NAME=emqx@node1.emqx.io"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    volumes:
      - ./dc/message-broker/data:/opt/emqx/data
      - ./dc/message-broker/logs:/opt/emqx/log
      - ./dc/message-broker/etc:/opt/emqx/etc
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083

  database:
    image: postgres
    restart: always
    environment:
      - "POSTGRES_PASSWORD=pg@dm1n"
    volumes:
      - ./dc/database/data:/var/lib/postgresql/data
    ports:
      - 8000:5432

  iot:
    build:
      context: ./src
      dockerfile: Dockerfile.IoT
    depends_on:
      message-broker:
        condition: service_healthy
      database:
        condition: service_started
    ports:
      - 5001:5001

  authentication:
    build:
      context: ./src
      dockerfile: Dockerfile.Authentication
    depends_on:
      database:
        condition: service_started
    ports:
      - 5011:5001

  api:
    build:
      context: ./src
      dockerfile: Dockerfile.API
    depends_on:
      - iot
      - authentication
    ports:
      - 8080:8080
